# Generated by Django 3.0 on 2025-03-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='REQUEST',
        ),
        migrations.AddField(
            model_name='payment',
            name='SERVICEPLAN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Serviceplan'),
            preserve_default=False,
        ),
    ]
