# Generated by Django 3.0 on 2025-03-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250319_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='TRAINER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Trainer'),
            preserve_default=False,
        ),
    ]
