# Generated by Django 3.0 on 2025-03-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_review_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='FROM',
            new_name='FROMID',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='TO',
            new_name='TOID',
        ),
    ]
