# Generated by Django 3.0 on 2025-03-20 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20250319_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='TRAINER',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='TRAINER',
        ),
        migrations.AddField(
            model_name='classes',
            name='REQUEST',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tips',
            name='REQUEST',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Request'),
            preserve_default=False,
        ),
    ]
