# Generated by Django 3.0 on 2025-03-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250320_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fromtime', models.TimeField()),
                ('totime', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Trainer')),
            ],
        ),
    ]
