# Generated by Django 4.2.16 on 2025-03-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='TRAINER',
        ),
    ]
