# Generated by Django 4.2.16 on 2025-03-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_complaint_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_profle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Age', models.DateField()),
                ('Obicity', models.CharField(max_length=100)),
                ('Bloodpressure', models.CharField(max_length=100)),
                ('Diabetes', models.CharField(max_length=100)),
                ('Cholestrol', models.CharField(max_length=100)),
                ('Alcoholabuse', models.CharField(max_length=100)),
                ('Druguse', models.CharField(max_length=100)),
                ('Smoking', models.CharField(max_length=100)),
                ('Headaches', models.CharField(max_length=100)),
                ('Asthma', models.CharField(max_length=100)),
                ('Heartproblem', models.CharField(max_length=100)),
                ('Cancer', models.CharField(max_length=100)),
                ('Stroke', models.CharField(max_length=100)),
                ('Bone_joint', models.CharField(max_length=100)),
                ('Kidney', models.CharField(max_length=100)),
                ('Liver', models.CharField(max_length=100)),
                ('Depression', models.CharField(max_length=100)),
                ('Allergies', models.CharField(max_length=100)),
                ('Arthritis', models.CharField(max_length=100)),
                ('Pregnancy', models.CharField(max_length=100)),
                ('bmi', models.FloatField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
