# Generated by Django 3.2.25 on 2025-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_diet_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
