# Generated by Django 3.2.25 on 2025-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_tips_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='free_riding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='group_classes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='nutrition_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='personal_trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='sauna_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='swimming_pool_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='unlimited_equipment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='weight_loss_classes',
            field=models.BooleanField(default=False),
        ),
    ]
